coordinator=true

# Không cho Coordinator chạy task xử lý dữ liệu
node-scheduler.include-coordinator=false

# Port nội bộ của Trino
http-server.http.port=8080

# Địa chỉ discovery service
discovery.uri=http://trino-coordinator:8080